# Generated by Django 6.0.5 on 2026-08-05 06:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
        ('goals', '0002_goal_completed_at_goal_previous_obstacles_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardtask',
            options={'ordering': ['sort_order', 'created_at']},
        ),
        migrations.AddField(
            model_name='boardtask',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boardtask',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boardtask',
            name='importance',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='small', max_length=20),
        ),
        migrations.AddField(
            model_name='boardtask',
            name='position_x',
            field=models.PositiveIntegerField(default=5000, help_text='Horizontal position inside the current Board zone, stored as a normalized value from 0 to 10000.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)]),
        ),
        migrations.AddField(
            model_name='boardtask',
            name='position_y',
            field=models.PositiveIntegerField(default=5000, help_text='Vertical position inside the current Board zone, stored as a normalized value from 0 to 10000.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)]),
        ),
        migrations.AddField(
            model_name='boardtask',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='boardtask',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='boardtask',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('goal_ai', 'Goal AI'), ('daily_log', 'Daily Log')], default='manual', max_length=20),
        ),
        migrations.CreateModel(
            name='BoardTaskDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('depends_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependent_links', to='board.boardtask')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependency_links', to='board.boardtask')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='boardtask',
            name='dependencies',
            field=models.ManyToManyField(blank=True, related_name='dependent_tasks', through='board.BoardTaskDependency', through_fields=('task', 'depends_on'), to='board.boardtask'),
        ),
        migrations.AddIndex(
            model_name='boardtask',
            index=models.Index(fields=['goal', 'status', 'sort_order'], name='board_goal_status_order_idx'),
        ),
        migrations.AddIndex(
            model_name='boardtask',
            index=models.Index(fields=['goal', 'due_date'], name='board_goal_due_date_idx'),
        ),
        migrations.AddIndex(
            model_name='boardtask',
            index=models.Index(fields=['status', 'priority'], name='board_status_priority_idx'),
        ),
        migrations.AddIndex(
            model_name='boardtaskdependency',
            index=models.Index(fields=['task', 'depends_on'], name='board_dependency_pair_idx'),
        ),
        migrations.AddConstraint(
            model_name='boardtaskdependency',
            constraint=models.UniqueConstraint(fields=('task', 'depends_on'), name='unique_board_task_dependency'),
        ),
        migrations.AddConstraint(
            model_name='boardtaskdependency',
            constraint=models.CheckConstraint(condition=models.Q(('task', models.F('depends_on')), _negated=True), name='board_task_cannot_depend_on_itself'),
        ),
    ]
