# Generated by Django 6.0.5 on 2026-08-10 07:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_habitcompletion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={'ordering': ['status', '-updated_at']},
        ),
        migrations.AddField(
            model_name='habit',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='habitcompletion',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('missed', 'Missed')], default='completed', max_length=20),
        ),
        migrations.AddIndex(
            model_name='habit',
            index=models.Index(fields=['user', 'status'], name='habit_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='habitcompletion',
            index=models.Index(fields=['habit', '-completed_at'], name='habit_completion_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='habitcompletion',
            constraint=models.UniqueConstraint(fields=('habit', 'completed_at'), name='unique_habit_day'),
        ),
    ]
