# Generated by Django 6.0.5 on 2026-07-30 05:24

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wins', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='win',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AddField(
            model_name='win',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='win',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='win',
            name='event_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='win',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('daily_log', 'Daily Log'), ('goal', 'Goal'), ('board', 'Board'), ('habit', 'Habit'), ('library', 'Library'), ('finance', 'Finance'), ('progress_photo', 'Progress Photo')], default='manual', max_length=30),
        ),
        migrations.AddField(
            model_name='win',
            name='source_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='win',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name='win',
            constraint=models.UniqueConstraint(condition=models.Q(('event_key__isnull', False)), fields=('user', 'event_key'), name='unique_win_event_per_user'),
        ),
    ]
