# Generated by Django 6.0.5 on 2026-07-30 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_logs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLogSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion_type', models.CharField(choices=[('win', 'Win'), ('goal', 'Goal'), ('book', 'Book'), ('habit', 'Habit'), ('context', 'Context')], default='win', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='small', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('suggestion_key', models.CharField(max_length=64)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='dailylog',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='dailylog',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_daily_log_per_user_date'),
        ),
        migrations.AddField(
            model_name='dailylogsuggestion',
            name='daily_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='daily_logs.dailylog'),
        ),
        migrations.AddIndex(
            model_name='dailylogsuggestion',
            index=models.Index(fields=['daily_log', 'status'], name='daily_log_suggestion_status_idx'),
        ),
        migrations.AddIndex(
            model_name='dailylogsuggestion',
            index=models.Index(fields=['suggestion_type', 'status'], name='suggestion_type_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailylogsuggestion',
            constraint=models.UniqueConstraint(fields=('daily_log', 'suggestion_key'), name='unique_suggestion_per_daily_log'),
        ),
    ]
