# Generated by Django 6.0.5 on 2026-07-30 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily_logs', '0002_daily_log_new'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dailylogsuggestion',
            new_name='dlog_sugg_status_idx',
            old_name='daily_log_suggestion_status_idx',
        ),
        migrations.RenameIndex(
            model_name='dailylogsuggestion',
            new_name='sugg_type_status_idx',
            old_name='suggestion_type_status_idx',
        ),
    ]
